[package]
name = "htmf-bots"
version = "0.1.0"
authors = ["Jeff Hemphill <jthemphill@gmail.com>"]
edition = "2021"

[dependencies]
arrayvec = "0.7"
getrandom = "0.2"
rand = "0.8"
rayon = "1.5"

htmf = { path = "../engine" }

[dev-dependencies]
criterion = "0.3"

[features]
wasm = [
    "getrandom/js",
]

[[bench]]
name = "minimax_full_game"
harness = false
