[package]
name = "htmf-bots"
version = "0.1.0"
authors = ["Jeff Hemphill <jthemphill@gmail.com>"]

[dependencies]
rand = "0.7.2"
rayon = "1.2.1"
smallvec = "1.0.0"

htmf = { path = "../engine" }

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "minimax_full_game"
harness = false
