[package]
name = "htmf-bots"
version = "0.1.0"
authors = ["Jeff Hemphill <jthemphill@gmail.com>"]

[dependencies]
arrayvec = "0.5"
rand = "0.7"
rayon = "1.4"

htmf = { path = "../engine" }

[dev-dependencies]
criterion = "0.3"

[features]
wasm = [
    "rand/wasm-bindgen",
]

[[bench]]
name = "minimax_full_game"
harness = false
