[package]
name = "htmf-server"
version = "0.1.0"
authors = ["Jeff Hemphill <jthemphill@gmail.com>"]

[dependencies]
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tungstenite = "0.11"

htmf = { path = "../engine" }
htmf-bots = { path = "../bots" }
