[package]
name = "htmf-server"
version = "0.1.0"
authors = ["Jeff Hemphill <jthemphill@gmail.com>"]

[dependencies]
rand = "0.7.2"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
tungstenite = "0.9.2"

htmf = { path = "../engine" }
htmf-bots = { path = "../bots" }
